spring.application.name=api
cari.wallet.mock-enabled=true
cari.base-url=http://localhost:8080
cari.x-api-key=alfanlckas
rest.client.connect-timeout-millis=3000
rest.client.read-timeout-millis=10000

api.gateway.key=asd_aswef

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
